before:
  hooks:
    - go mod tidy
builds:
  -
    id: default
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
      - freebsd
      - solaris
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
    goarm:
      - "6"
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -s -w
upx:
  -
    ids: [ default ]
    enabled: true
    goos: ["windows", "linux"]
    goarch: ["amd64", "386"]
    compress: best
#    lzma: true
#    brute: true
archives:
  -
    format: binary
    allow_different_binary_count: true
    name_template: >-
      {{- .ProjectName }}
      {{- if eq .Os "darwin"}}_mac
      {{- else if eq .Os "linux"}}_linux
      {{- else if eq .Os "windows"}}_windows
      {{- else }}_{{ .Os }}{{ end }}
      {{- if eq .Arch "amd64" }}_amd64
      {{- else if eq .Arch "386" }}_386
      {{- else }}_{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
  - id: all
    format: zip
    name_template: "{{ .ProjectName }}_all"
    files:
      - "{{ .ProjectName }}_windows_386.exe"
      - "{{ .ProjectName }}_windows_amd64.exe"
      - "{{ .ProjectName }}_windows_arm64.exe"
      - "{{ .ProjectName }}_windows_armv6.exe"
      - "{{ .ProjectName }}_windows_armv7.exe"
      - "{{ .ProjectName }}_linux_386"
      - "{{ .ProjectName }}_linux_amd64"
      - "{{ .ProjectName }}_linux_arm64"
      - "{{ .ProjectName }}_linux_armv6"
      - "{{ .ProjectName }}_linux_armv7"
      - "{{ .ProjectName }}_linux_mips"
      - "{{ .ProjectName }}_linux_mips64"
      - "{{ .ProjectName }}_linux_mipsle"
      - "{{ .ProjectName }}_mac_amd64"
      - "{{ .ProjectName }}_mac_arm64"
      - "{{ .ProjectName }}_freebsd_386"
      - "{{ .ProjectName }}_freebsd_amd64"
      - "{{ .ProjectName }}_freebsd_arm64"
      - "{{ .ProjectName }}_freebsd_armv6"
      - "{{ .ProjectName }}_freebsd_armv7"
      - "{{ .ProjectName }}_solaris_amd64"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - "^*.ya?ml"